import type { NextPage } from 'next';
import Head from 'next/head';
import { useDispatch, useSelector } from 'react-redux';
import { add } from 'src/store/cartSlice';
import { RootState } from 'src/store/store';

const Home: NextPage = () => {
    const { cart } = useSelector((state: RootState) => state.cart);
    const dispatch = useDispatch();

    const addToCartHandler = () => {
        dispatch(add({ name: 'string', price: 1, quantity: 1 }));
    };

    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>This is main section</main>
            <footer>Footer section</footer>
        </div>
    );
};

export default Home;
